import type { Metadata } from "next";
import { Jaro, Jura  } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const jaroFont = Jaro({
  variable: "--font-jaro",
  subsets: ["latin"],
});

export const juraFont = Jura({
  variable: "--font-jura",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sandwiriffic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${juraFont.className} antialiased`}
      >
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
