import type { Metadata } from "next";
import "@/assets/styles/globals.css";
import { juraFont } from "@/assets/fonts/fonts";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Sandwiriffic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${juraFont.className} antialiased`}>
        {/* <Navbar /> */}
        <main>{children}</main>
      </body>
    </html>
  );
}
